version: '2'

services:

    mongodb:
        image: mongo:3.4
        networks:
            elk:
                ipv4_address: 172.19.1.3
    
    nginx:
        networks:
            elk:
                ipv4_address: 172.19.1.4


networks:
    elk:
        ipam:
            config:
                - driver: default
                  subnet: 172.18.1.0/24
                  gateway: 172.19.1.1
