version: '2'

services:

    redis:
        image: redis:4.0 
        ports:
          - 6379:6379
        volumes:
          - ./data/redis:/data
        networks:
            pene:
                ipv4_address: 172.18.1.2

    mongodb:
        build: ./mongodb
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
        ports:
          - 27017:27017
        volumes:
          - ./data/mongodb/:/data/db
          - ./logs:/logs
        networks:
            pene:
                ipv4_address: 172.18.1.3
    
    nginx:
        build: ./backend
        container_name: "penework"
        ports: 
            - "80:80"
        volumes:
            - ./frontend/dist:/var/www/penework
            - ./backend/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./backend/app:/app
            - ./backend/uwsgi.ini:/etc/uwsgi/uwsgi.ini
        links:
            - mongodb
        networks:
            pene:
                ipv4_address: 172.18.1.4


networks:
    pene:
        ipam:
            config:
                - driver: default
                  subnet: 172.18.1.0/24
                  gateway: 172.18.1.1
