version: '2'

services:

    redis:
        image: redis:4.0 
        networks:
            pene:
                ipv4_address: 172.19.1.2

    mongodb:
        image: mongo:3.4
        volumes:
            - ./data/mongodb:/data
        networks:
            pene:
                ipv4_address: 172.19.1.3
    
    nginx:
        build: ./backend
        name: penework_server
        ports: 
            - "12345":"12345" # for backend
            - "80":80
        volumes:
            - ./fontend
        networks:
            pene:
                ipv4_address: 172.19.1.4


networks:
    pene:
        ipam:
            config:
                - driver: default
                  subnet: 172.18.1.0/24
                  gateway: 172.19.1.1
