version: '2'

services:
    fontend:
        build: mysql/
        volumes:
            - ./mysql/mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            
        networks:
            elk:
                ipv4_address: 172.18.1.3

    backend:
        build: app/
        volumes:
            - ./web/app:/app/
        ports:
            - "9191:80"
        networks:
            elk:
                ipv4_address: 172.18.1.4

networks:
    elk:
        ipam:
            config:
                - driver: default
                  subnet: 172.18.1.0/24
                  gateway: 172.18.1.1
